locals {
  github_repositories = {
    "magnolia" = {
      description            = "[mirror] interactive shell navigation and history"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = false
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = "https://codeberg.org/mtmn/magnolia"
      topics                 = []
    },
    "dotfiles" = {
      description            = "[mirror] configuration files i use on linux"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = false
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = "https://codeberg.org/mtmn/dotfiles"
      topics                 = []
    },
    "tools" = {
      description            = "[mirror] various tools I have been using throughout the years"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = false
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = "https://codeberg.org/mtmn/tools"
      topics                 = []
    },
    "plants" = {
      description            = "[mirror] bluetooth battery monitoring for linux"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = false
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = "https://codeberg.org/mtmn/plants"
      topics                 = []
    },
    "bobor-status" = {
      description            = "[mirror] bluetooth battery monitoring for linux"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = false
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = "https://codeberg.org/mtmn/bobor-status"
      topics                 = []
    },
    "cdk-demo" = {
      description            = "Deploy nginx into AWS Fargate using CDK Toolkit"
      visibility             = "public"
      has_issues             = false
      has_projects           = false
      has_wiki               = false
      has_discussions        = false
      allow_merge_commit     = true
      allow_squash_merge     = false
      allow_rebase_merge     = false
      allow_auto_merge       = false
      delete_branch_on_merge = false
      vulnerability_alerts   = false
      archive_on_destroy     = false
      auto_init              = false
      gitignore_template     = null
      license_template       = null
      homepage_url           = null
      topics                 = []
    },
  }
}

