FROM ghcr.io/rust-cross/cargo-zigbuild:latest

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && \
apt-get install libswscale-dev libavdevice-dev libavfilter-dev libavcodec-dev libavformat-dev libavutil-dev --yes
